repos:
  - repo: local
    hooks:
      - id: no-chinese
        name: No Chinese Characters in Code
        entry: python ./format_check/check.py
        language: system
        types: [python]
        args: []
        exclude: ^docs/|/tests/|/venv/|/env/|__pycache__/